Repository robotique-udes/rover, pull requests merged in 2025-06, with the labels that each got.

#147 Dev/GUI top bar
  rover_gui/CMakeLists.txt
  rover_gui/src/Global/Constant/TaskDateAndTime.txt
  rover_gui/src/Global/Constant/resources.qrc
  rover_gui/src/Global/Helpers/QToastNotification/QToastNotification.cpp
  rover_gui/src/MainWindow.cpp
  rover_gui/src/MainWindow.hpp
  rover_gui/src/QTopUtilityBar/QTopUtilityBar.cpp
  rover_gui/src/QTopUtilityBar/QTopUtilityBar.hpp
  rover_gui/ui/icons.qrc
  rover_gui/ui/icons/BatteryError.svg
  rover_gui/ui/icons/BatteryIcon0.svg
  rover_gui/ui/icons/BatteryIcon100.svg
  rover_gui/ui/icons/BatteryIcon25.svg
  rover_gui/ui/icons/BatteryIcon50.svg
  rover_gui/ui/icons/BatteryIcon75.svg
  rover_gui/ui/icons/ErrorRSSI.png
  rover_gui/ui/icons/GNSSError.svg
  rover_gui/ui/icons/GNSSIcon.svg
  rover_gui/ui/icons/HeadingError.svg
  rover_gui/ui/icons/HeadingIcon.svg
  rover_gui/ui/icons/RSSI_four.png
  rover_gui/ui/icons/RSSI_one.png
  rover_gui/ui/icons/RSSI_three.png
  rover_gui/ui/icons/RSSI_two.png
  rover_gui/ui/ui/TopUtilityBar.ui
  rover_msgs/CMakeLists.txt
  rover_msgs/msg/Battery.msg
  rover_msgs/msg/Gps.msg
  rover_msgs/msg/WifiConnection.msg
  rover_sim/CMakeLists.txt
  rover_sim/launch/sim.launch.py
  rover_sim/package.xml
  rover_sim/src/battery_test_pub.cpp
  rover_sim/src/connection_speed_test_pub.cpp
  rover_sim/src/gps_test_pub.cpp
  scripts/provision.sh
Labels: New feature

#170 Multiple minor code quality improvement
  .github/workflows/build_packages.yml
  .github/workflows/lint-cpp.yml
  .github/workflows/rover_shared_lib_matches_rover_micro.yml
  rover_arm/include/arm_configuration.hpp
  rover_arm/include/cartesian_controller.hpp
  rover_arm/include/joint_controller.hpp
  rover_arm/include/joy_manager.hpp
  rover_arm/include/keybinding.hpp
  rover_arm/include/robot_controller.hpp
  rover_arm/src/teleop.cpp
  rover_auxiliary/src/DDB/ddb_control_node.cpp
  rover_auxiliary/src/DDB/ddb_control_node.hpp
  rover_camera/src/aruco_detection/aruco_detection_node.cpp
  rover_camera/src/aruco_detection/aruco_detection_node.hpp
  rover_camera/src/aruco_detection/detection.cpp
  rover_camera/src/aruco_detection/detection.hpp
  rover_camera/src/aruco_detection/image_capture.cpp
  rover_camera/src/aruco_detection/image_capture.hpp
  rover_camera/src/aruco_detection/process_frame.cpp
  rover_camera/src/aruco_detection/process_frame.hpp
  rover_camera/src/camera_node.hpp
  rover_drive_train/src/arbitration.cpp
  rover_drive_train/src/teleop.cpp
  rover_shared_libs/CMakeLists.txt
  rover_shared_libs/rover_lib2/src/rover_lib2/helpers/constants.hpp
  rover_shared_libs/rover_lib2/src/rover_lib2/helpers/log.hpp
  rover_shared_libs/rover_lib2/src/rover_lib2/helpers/macros.hpp
  scripts/cansend_helper.py
Labels: Improvement

#178 Dashboard + small improvements
  rover_gui/CMakeLists.txt
  rover_gui/src/Global/Constant/StyleSheet.hpp
  rover_gui/src/Global/Constant/other/map.html
  rover_gui/src/MainWindow.cpp
  rover_gui/src/MainWindow.hpp
  rover_gui/src/QArbitration/QArbitration.cpp
  rover_gui/src/QArbitration/QArbitration.hpp
  rover_gui/src/QDashboard/QDashboard.cpp
  rover_gui/src/QDashboard/QDashboard.hpp
  rover_gui/src/QDashboard/QExample.cpp
  rover_gui/src/QDashboard/QExample.hpp
  rover_gui/src/QDeviceStatus/QDeviceStatus.cpp
  rover_gui/src/QDeviceStatus/QDeviceStatus.hpp
  rover_gui/src/QNavigation/QNavigation.cpp
  rover_gui/src/QNavigation/QNavigation.hpp
  rover_gui/src/QScreenInhibitor.cpp
  rover_gui/src/QScreenInhibitor.hpp
  rover_gui/src/QSideBar/QSideBar.cpp
  rover_gui/src/QSideBar/QSideBar.hpp
  rover_gui/src/QSshFileExplorer/QFileTransferWidget.cpp
  rover_gui/src/QSshFileExplorer/QFileTransferWidget.hpp
  rover_gui/src/QUtilityBarBottom/QUtilityBarBottom.hpp
  rover_gui/src/QUtilityBarTop/QUtilityBarTop.cpp
  rover_gui/src/QUtilityBarTop/QUtilityBarTop.hpp
  rover_gui/src/QVideoPlayer/QVideoManagerWidget.cpp
  rover_gui/src/gui.cpp
  rover_gui/ui/ui/Arbitration.ui
  rover_gui/ui/ui/DeviceStatus.ui
  rover_gui/ui/ui/Navigation.ui
  rover_gui/ui/ui/TopUtilityBar.ui
  rover_gui/ui/ui/UtilityBarBottom.ui
Labels: New feature, Improvement
