Repository robotique-udes/rover, pull requests merged in 2025-04, with the labels that each got.

#117 Small changes to VideoPlayer and CameraInfo
  rover_gui/CMakeLists.txt
  rover_gui/src/QVideoPlayer/QVideoManagerWidget.cpp
  rover_gui/src/QVideoPlayer/QVideoManagerWidget.hpp
  rover_gui/src/QVideoPlayer/QVideoPlayerWidget.cpp
  rover_gui/src/QVideoPlayer/QVideoPlayerWidget.hpp
  rover_gui/ui/ui/VideoPlayer.ui
  rover_msgs/CMakeLists.txt
  rover_msgs/include/rovus_lib/camera_info.cpp
  rover_msgs/include/rovus_lib/camera_info.hpp
  rover_video/src/camera_node.cpp
Labels: Bugfix

#121 [GUI] Fixed GUI not exiting on window closed + Added Ctrl+W exit + Made gui exit on any window closed
  rover_gui/src/Global/Constant/Keybinding.hpp
  rover_gui/src/Global/Constant/StyleSheet.hpp
  rover_gui/src/MainWindow.cpp
  rover_gui/src/MainWindow.hpp
  rover_gui/src/SecondaryWindow.cpp
  rover_gui/src/SecondaryWindow.hpp
  rover_gui/src/gui.cpp
Labels: Bugfix, New feature

#120 [GUI] Switched to current user instead of hardcoded phil user in filetransfer widget
  rover_gui/src/Global/Helpers/QHelpers.cpp
  rover_gui/src/Global/Helpers/QHelpers.hpp
  rover_gui/src/QSshFileExplorer/QFileTransferWidget.cpp
Labels: Bugfix

#123 missing logger include in can_msg.hpp
  rover_shared_libs/rover_can2/src/rover_can2/can_msg.hpp
Labels: Bugfix

#119 Helpers scripts for canbus debugging
  scripts/can_bandwidth.sh
  scripts/cansend_helper.py
  scripts/provision.sh
Labels: New feature
